# Generated by Django 6.0.3 on 2026-03-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('position_title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Applied', 'applied'), ('Interview', 'interview'), ('Rejected', 'rejected'), ('Offer', 'offer')], max_length=20)),
                ('date_applied', models.DateField()),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
